#!/bin/sh
#
# Copyright (c) 2012 F-Secure Corporation. All Rights Reserved.
#

PREFIX=/usr/share
BASE_DIR=$PREFIX/dvmps/conf

echo
echo "Dynamic Virtual Machine Provisioning Service Node Setup"
echo "======================================================="
echo

if [ `whoami` != 'root' ]; then
    echo "This script must be executed as 'root'."
    echo "Setup aborted."
    exit 1
fi

sh $BASE_DIR/check_kvm
if [ $? -ne 0 ]; then
    echo -n "Continue with setup? [y/N] "
    read CONFIRM_KVM
    if [ ! "$CONFIRM_KVM" = "Y" -a ! "$CONFIRM_KVM" = "y" ]; then
        echo "Setup aborted."
        exit 1
    fi
fi

#TODO: currently only the default image directory works
#DEFAULT_IMAGEDIR=/var/lib/libvirt/images
#echo -n "Please specify the libvirt image directory [$DEFAULT_IMAGEDIR]: "
#read IMAGEDIR
#
#if [ -z "$IMAGEDIR" ]; then
#    IMAGEDIR=$DEFAULT_IMAGEDIR
#fi
#
#echo -n "$IMAGEDIR? [Y/n] "
#read CONFIRM
#if [! -d "$IMAGEDIR" ]; then
#    echo "Creating directory $IMAGEDIR"
#    mkdir -p $IMAGEDIR
#fi


# TODO fix setup_tmpfs to follow packaging guidelines
echo -n "Set up tmpfs? [y/N] "
read CONFIRM_TMPFS
if [ "$CONFIRM_TMPFS" = "Y" -o "$CONFIRM_TMPFS" = "y" ]; then
    sh $BASE_DIR/setup_tmpfs
fi

echo -n "Set up database? [y/N] "
read CONFIRM_DATABASE
if [ "$CONFIRM_DATABASE" = "Y" -o "$CONFIRM_DATABASE" = "y" ]; then
    sh $BASE_DIR/setup_database
fi

echo -n "Set up DHCP server configurations? [y/N] "
read CONFIRM_DHCPD
if [ "$CONFIRM_DHCPD" = "Y" -o "$CONFIRM_DHCPD" = "y" ]; then
    sh $BASE_DIR/setup_dhcpd
fi

echo -n "Set up network configurations? [y/N] "
read CONFIRM_NETWORK
if [ "$CONFIRM_NETWORK" = "Y" -o "$CONFIRM_NETWORK" = "y" ]; then
    sh $BASE_DIR/setup_network
fi

echo -n "Restart DVMPS? [Y/n] "
read CONFIRM_DVMPS
if [ "$CONFIRM_DVMPS" != "N" -a "$CONFIRM_DVMPS" != "n" ]; then
    service dvmps restart
fi

sh $BASE_DIR/setup_httpd status
if [ $? -eq 0 ]; then
    echo -n "    Disable web server? [y/N] "
    read CONFIRM_HTTPD
    if [ "$CONFIRM_HTTPD" = "Y" -o "$CONFIRM_HTTPD" = "y" ]; then
        sh $BASE_DIR/setup_httpd disable
    fi
else
    echo -n "    Enable web server? [y/N] "
    read CONFIRM_HTTPD
    if [ "$CONFIRM_HTTPD" = "Y" -o "$CONFIRM_HTTPD" = "y" ]; then
        sh $BASE_DIR/setup_httpd enable
    fi
fi

if [ -d /etc/munin/plugins -a -e $PREFIX/munin/plugins/dvmps_dirsizes ]; then
    sh $BASE_DIR/setup_munin status
    if [ $? -eq 0 ]; then
        echo -n "    Disable Munin node? [y/N] "
        read CONFIRM_MUNIN_NODE
        if [ "$CONFIRM_MUNIN_NODE" = "Y" -o "$CONFIRM_MUNIN_NODE" = "y" ]; then
            sh $BASE_DIR/setup_munin disable
        fi
    else
        echo -n "    Enable Munin node? [y/N] "
        read CONFIRM_MUNIN_NODE
        if [ "$CONFIRM_MUNIN_NODE" = "Y" -o "$CONFIRM_MUNIN_NODE" = "y" ]; then
           sh $BASE_DIR/setup_munin enable
        fi
    fi
else
    echo "Install munin-node and munin-dvmps-plugins for configuring Munin node"
fi

echo ""

