#!/bin/sh
#
# Copyright (c) 2012 F-Secure Corporation. All Rights Reserved.
#

BASEDIR=/var/lib/libvirt/dvmps_active
MTAB=/etc/mtab
FSTAB=/etc/fstab
FSTAB_BAK=/etc/fstab.bak

TEMP_FSTAB=/tmp/fstab.tmp.$$

trap "rm -f $TEMP_FSTAB" EXIT

# setup tmpfs
TMPFS_MNT=$BASEDIR/images

TMPFS=`grep -E 'tmpfs|ramfs' $FSTAB | grep $BASEDIR`
if [ $? -eq 0 ]; then 
    echo
    echo $TMPFS
    echo -n "tmpfs are already configured, skip? [Y/n] "
    read CONFIRM
    if [ -z "$CONFIRM" -o "$CONFIRM" = "Y" -o "$CONFIRM" = "y" ]; then
        echo "tmpfs setup skipped"
        exit 0
    fi
fi

echo -n "Enter tmpfs size (supported suffix: K, M, G): "
read SIZE

echo "Generating file $FSTAB..."
if [ -n "$TMPFS" ]; then
    TMPFS_N=`echo $TMPFS | cut -f1 -d:`
    sed -e ${TMPFS_N}d $FSTAB > $TEMP_FSTAB
else
    cat $FSTAB > $TEMP_FSTAB
fi
echo "tmpfs $TMPFS_MNT tmpfs size=$SIZE 0 0" >> $TEMP_FSTAB

# output generate file

echo
echo "===== $FSTAB ====="
cat $TEMP_FSTAB

# confirm update

echo -n "Update? [Y/n] "
read CONFIRM

if [ -z "$CONFIRM" -o "$CONFIRM" = "Y" -o "$CONFIRM" = "y" ]; then
    echo
    echo "Updating file $FSTAB..."
    mv $FSTAB $FSTAB_BAK
    mv $TEMP_FSTAB $FSTAB

    if grep -E 'tmpfs|ramfs' $MTAB | grep -q $TMPFS_MNT ; then
        echo "Unmounting $TMPFS_MNT..."
        umount $TMPFS_MNT
    fi

    echo "Mounting $TMPFS_MNT..."
    mount $TMPFS_MNT

    echo "Done."
else
    echo "Aborted."
fi
