#!/bin/sh

PREFIX=/usr/share

service dvmps stop

sh $PREFIX/dvmps/conf/setup_httpd disable

# destroy dvmps database
if [ "$1" != "upgrade" ]; then
    echo "Deleting DVMPS database"
    dropdb dvmps
else
    echo "Upgrading so not deleting the database"
fi

# remove generated pyc files
rm -f $PREFIX/dvmps/*.pyc
rm -f $PREFIX/dvmps/conf/py/*.pyc

# remove link
rm /usr/sbin/dvmps-setup

# remove log dirs and logs
rm -rf /var/log/dvmps
rm -rf /var/run/dvmps

