#!/bin/sh
#
# Copyright (c) 2012 F-Secure Corporation. All Rights Reserved.
#

HTTPD_INIT=/etc/init.d/nginx
BASEDIR=/etc/nginx
DVMPS_SITE=/opt/dvmps/extra/dvmps.nginx-site

install -m 0644 $DVMPS_SITE $BASEDIR/sites-available/dvmps
ln -sf $BASEDIR/sites-available/dvmps $BASEDIR/sites-enabled/default

echo "Stopping web server..."
$HTTPD_INIT stop

echo "Starting web server..."
$HTTPD_INIT start

echo "Done."
