#!/bin/sh
#
# Copyright (c) 2012 F-Secure Corporation. All Rights Reserved.
#

BASE_DIR=/opt/dvmps/setup_scripts

echo
echo "Dynamic Virtual Machine Provisioning Service Node Setup"
echo "======================================================="
echo

if [ `whoami` != 'root' ]; then
    echo "This script must be executed as 'root'."
    echo "Setup aborted."
    exit 1
fi

echo -n "Set up APT? [y/N] "
read CONFIRM_APT
if [ "$CONFIRM_APT" = "Y" -o "$CONFIRM_APT" = "y" ]; then
    $BASE_DIR/setup_apt
fi

echo -n "Update packages? [y/N] "
read CONFIRM_PKG
if [ "$CONFIRM_PKG" = "Y" -o "$CONFIRM_PKG" = "y" ]; then
    apt-get update
    apt-get -fy install
fi

$BASE_DIR/check_kvm

if [ $? -ne 0 ]; then
    echo -n "Continue with setup? [y/N] "
    read CONFIRM_KVM
    if [ ! "$CONFIRM_KVM" = "Y" -a ! "$CONFIRM_KVM" = "y" ]; then
        echo "Setup aborted."
        exit 1
    fi
fi

echo -n "Is VLAN required? [y/N] "
read CONFIRM_VLAN
if [ "$CONFIRM_VLAN" = "Y" -o "$CONFIRM_VLAN" = "y" ]; then
    apt-get -y install vlan
fi

echo -n "Set up network? [y/N] "
read CONFIRM_NETWORK
if [ "$CONFIRM_NETWORK" = "Y" -o "$CONFIRM_NETWORK" = "y" ]; then
    $BASE_DIR/setup_network
fi

echo -n "Set up libvirt? [y/N] "
read CONFIRM_LIBVIRT
if [ "$CONFIRM_LIBVIRT" = "Y" -o "$CONFIRM_LIBVIRT" = "y" ]; then
    $BASE_DIR/setup_libvirt
fi

echo -n "Set up database? [y/N] "
read CONFIRM_DATABASE
if [ "$CONFIRM_DATABASE" = "Y" -o "$CONFIRM_DATABASE" = "y" ]; then
    $BASE_DIR/setup_database
fi

echo -n "Set up web server? [y/N] "
read CONFIRM_HTTPD
if [ "$CONFIRM_HTTPD" = "Y" -o "$CONFIRM_HTTPD" = "y" ]; then
    $BASE_DIR/setup_httpd
fi

echo -n "Set up DHCP server? [y/N] "
read CONFIRM_DHCPD
if [ "$CONFIRM_DHCPD" = "Y" -o "$CONFIRM_DHCPD" = "y" ]; then
    $BASE_DIR/setup_dhcpd
fi

echo -n "Set up cron? [y/N] "
read CONFIRM_CRON
if [ "$CONFIRM_CRON" = "Y" -o "$CONFIRM_CRON" = "y" ]; then
    /etc/init.d/cron reload
fi

echo -n "Set up Munin node? [y/N] "
read CONFIRM_MUNIN_NODE
if [ "$CONFIRM_MUNIN_NODE" = "Y" -o "$CONFIRM_MUNIN_NODE" = "y" ]; then
    $BASE_DIR/setup_munin_node
fi

echo -n "Set up DVMPS? [y/N] "
read CONFIRM_DVMPS
if [ "$CONFIRM_DVMPS" = "Y" -o "$CONFIRM_DVMPS" = "y" ]; then
    update-rc.d dvmps defaults
fi

echo -n "Stop/start DVMPS? [y/N] "
if [ "$CONFIRM_DVMPS" = "Y" -o "$CONFIRM_DVMPS" = "y" ]; then
    /etc/init.d/dvmps stop
    /etc/init.d/dvmps start
fi

echo
echo "Setup done."
