#!/usr/bin/python

import sys
import subprocess

def call(command_and_args, shell=False):
    proc = subprocess.Popen(command_and_args, shell=shell, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (sout,serr) = proc.communicate()
    return (proc.returncode, sout, serr)

if len(sys.argv) == 2:
    if sys.argv[1] == "config":
        print "graph_title DVMPS - cloning rate"
        print "graph_vlabel clones per minute"
        print "graph_category Virtual Machines"
        print "clones.label clones"
        print "clones.type DERIVE"
        print "clones.min 0"
        print "clones.cdef clones,60,*"
        sys.exit(0)

(rc,out,err) = call('grep "successfully allocated image" /var/log/dvmps/dvmps.log | wc -l', shell=True)
if rc == 0:
    print "clones.value %s" % out.strip()

