#!/usr/bin/python

import sys
import urllib2
import json

if len(sys.argv) == 2:
    if sys.argv[1] == "config":
        o = urllib2.urlopen('http://localhost/base_images', json.dumps(None))
        d = o.read()
        i = json.loads(d)
        print "graph_title DVMPS - number of clones"
        print "graph_vlabel number of instances"
        print "graph_category Virtual Machines"
        print "graph_printf %3.0lf"

        for image in sorted(i['base_images']):
            image = image.replace(".", "_")
            print "%s.label %s" % (image, image)
            print "%s.draw AREASTACK" % image
        sys.exit(0)

images = {}
o = urllib2.urlopen('http://localhost/base_images', json.dumps(None))
d = o.read()
i = json.loads(d)

for image in i['base_images']:
    images[image] = 0

o = urllib2.urlopen('http://localhost/running_images', json.dumps(None))
d = o.read()
i = json.loads(d)

for image in i['running_images']:
    bi = image['base_image']
    if images.has_key(bi):
        images[bi] = images[bi] + 1 
    else:
        images[bi] = 1

for k in sorted(images.keys()):
    print "%s.value %d" % (k.replace(".", "_"), images[k])
